Repository ratingus/ratingus-backend, pull requests merged in 2024-05, with the labels that each got.

#18 RATINGUS-242 Добавил билд с зависимостями
  Dockerfile
  pom.xml
Labels: bug

#28 Расписание
  src/main/java/ru/dnlkk/ratingusbackend/api/ScheduleApi.java
  src/main/java/ru/dnlkk/ratingusbackend/api/controllers/ScheduleController.java
  src/main/java/ru/dnlkk/ratingusbackend/api/dtos/TeacherDTO.java
  src/main/java/ru/dnlkk/ratingusbackend/api/dtos/schedule/MergeSubjectWithTeacherRequestDTO.java
  src/main/java/ru/dnlkk/ratingusbackend/api/dtos/schedule/ScheduleActionDTO.java
  src/main/java/ru/dnlkk/ratingusbackend/api/dtos/schedule/ScheduleChangeDTO.java
  src/main/java/ru/dnlkk/ratingusbackend/api/dtos/schedule/ScheduleDTO.java
  src/main/java/ru/dnlkk/ratingusbackend/api/dtos/schedule/ScheduleDayDTO.java
  src/main/java/ru/dnlkk/ratingusbackend/api/dtos/schedule/ScheduleItemDTO.java
  src/main/java/ru/dnlkk/ratingusbackend/api/dtos/schedule/ScheduleTeachersDTO.java
  src/main/java/ru/dnlkk/ratingusbackend/model/Lesson.java
  src/main/java/ru/dnlkk/ratingusbackend/model/Schedule.java
  src/main/java/ru/dnlkk/ratingusbackend/model/StudentLesson.java
  src/main/java/ru/dnlkk/ratingusbackend/model/Subject.java
  src/main/java/ru/dnlkk/ratingusbackend/model/TeacherSubject.java
  src/main/java/ru/dnlkk/ratingusbackend/model/enums/Attendance.java
  src/main/java/ru/dnlkk/ratingusbackend/repository/ScheduleRepository.java
  src/main/java/ru/dnlkk/ratingusbackend/repository/UserRoleRepository.java
  src/main/java/ru/dnlkk/ratingusbackend/service/ScheduleService.java
Labels: feature

#33 RATINGUS-267 Подогнал бэк под нужды мобилки
  src/main/java/ru/dnlkk/ratingusbackend/api/AnnouncementApi.java
  src/main/java/ru/dnlkk/ratingusbackend/api/controllers/AnnouncementController.java
  src/main/java/ru/dnlkk/ratingusbackend/api/controllers/ProfileController.java
  src/main/java/ru/dnlkk/ratingusbackend/api/controllers/ScheduleController.java
  src/main/java/ru/dnlkk/ratingusbackend/api/dtos/announcement/AnnouncementDto.java
  src/main/java/ru/dnlkk/ratingusbackend/api/dtos/diary/LessonDto.java
  src/main/java/ru/dnlkk/ratingusbackend/api/dtos/schedule/ScheduleDayDTO.java
  src/main/java/ru/dnlkk/ratingusbackend/api/dtos/schedule/ScheduleItemDTO.java
  src/main/java/ru/dnlkk/ratingusbackend/mapper/announcement/AnnouncementMapper.java
  src/main/java/ru/dnlkk/ratingusbackend/model/enums/Role.java
  src/main/java/ru/dnlkk/ratingusbackend/security/JwtTokenService.java
  src/main/java/ru/dnlkk/ratingusbackend/service/AdminPanelService.java
  src/main/java/ru/dnlkk/ratingusbackend/service/AnnouncementService.java
  src/main/java/ru/dnlkk/ratingusbackend/service/DiaryService.java
  src/main/java/ru/dnlkk/ratingusbackend/service/MagazineService.java
  src/main/java/ru/dnlkk/ratingusbackend/service/ManagerPanelService.java
  src/main/java/ru/dnlkk/ratingusbackend/service/ScheduleService.java
  src/main/java/ru/dnlkk/ratingusbackend/service/UserService.java
  src/main/resources/application.yml
Labels: bug, feature

#37 RATINGUS-278 Модифицировать под нужды веб-морды
  src/main/java/ru/dnlkk/ratingusbackend/api/AdminPanelApi.java
  src/main/java/ru/dnlkk/ratingusbackend/api/ScheduleApi.java
  src/main/java/ru/dnlkk/ratingusbackend/api/config/SecurityConfig.java
  src/main/java/ru/dnlkk/ratingusbackend/api/config/WebConfig.java
  src/main/java/ru/dnlkk/ratingusbackend/api/controllers/AdminPanelController.java
  src/main/java/ru/dnlkk/ratingusbackend/api/controllers/ScheduleController.java
  src/main/java/ru/dnlkk/ratingusbackend/api/dtos/teacher_subject/TeacherSubjectsDto.java
  src/main/java/ru/dnlkk/ratingusbackend/api/dtos/teacher_subject/TeacherWithSubjectIdDto.java
  src/main/java/ru/dnlkk/ratingusbackend/service/AdminPanelService.java
  src/main/java/ru/dnlkk/ratingusbackend/service/ScheduleService.java
Labels: bug, feature
